version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Mapeia a porta do contêiner para a porta do host
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      - database  # Dependência no serviço do banco de dados

  database:
    image: postgres:latest  # Substitua pelo banco de dados que deseja usar
    environment:
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_db

